export const FB_LOGIN_STARTED = 'FB_LOGIN_STARTED';
export const FB_LOGIN_COMPLETED = 'FB_LOGIN_COMPLETED';
export const FB_LOGIN_FAILED = 'FB_LOGIN_FAILED';
export const FB_LOGIN_REDIRECTED = 'FB_LOGIN_REDIRECTED';
