export const FB_LOGIN_STARTED = 'FB_LOGIN_STARTED';
export const FB_LOGIN_COMPLETED = 'FB_LOGIN_COMPLETED';
export const FB_LOGIN_FAILED = 'FB_LOGIN_FAILED';
export const FB_LOGIN_REDIRECTED = 'FB_LOGIN_REDIRECTED';

export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_CONNECTION = 'SOCKET_CONNECTION';
export const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
export const SOCKET_CONNECTION_TIMEOUT = 'SOCKET_CONNECTION_TIMEOUT';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const SOCKET_RECONNECTING = 'SOCKET_RECONNECTING';
export const SOCKET_RECONNECTION = 'SOCKET_RECONNECTION';
export const SOCKET_RECONNECTION_FAILED = 'SOCKET_RECONNECTION_FAILED';
